# Generated by Django 3.1.1 on 2020-09-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='postdate',
            field=models.DateField(),
        ),
    ]
